package plugins.sage.timelapsereg;
// here this class is in the package - plugins.sage.timelapsereg

import icy.gui.dialog.MessageDialog;
import icy.plugin.abstract_.PluginActionable;

public class TimelapseReg extends PluginActionable {

	public void run() {
		// TODO Auto-generated by Icy4Eclipse
		MessageDialog.showDialog("TimelapseReg is working fine !");
	}

}
